
import Head from 'next/head'
import GlobalHeader from '../components/global/header/header'
import Modal from '../components/global/modal/modal'
import LoginForm from '../components/forms/login/login'
import React, { useState } from 'react';

export default function Home() {
  const [isModalActive, listenForModalTrigger] = useState(false)


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalHeader listenForModalTrigger={listenForModalTrigger}></GlobalHeader>
      <Modal isModalActive={isModalActive} modalTrigger={listenForModalTrigger}>
        <LoginForm></LoginForm>
      </Modal>
    </div>
  )
}
