
import Head from 'next/head'
import GlobalHeader from '../components/global/header/header'
import Modal from '../components/global/modal/modal'
import LoginForm from '../components/forms/login/login'
import React, { useState } from 'react';
import { signIn, signOut, useSession } from 'next-auth/react';

type PropTypes = {
  Component: any,
  pageProps: any
}

export default function Home({Component, pageProps} : PropTypes) {
  const {data: session} = useSession();
  const [isModalActive, setIsModalActive] = useState(false)


  function checkIfUserIsLoggedIn(session : Object | null ) {
    return session?.user ? true : false
  }

  return (
        <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <GlobalHeader setIsModalActive={setIsModalActive} isUserLoggedIn={checkIfUserIsLoggedIn(session)}></GlobalHeader>
        <Modal isModalActive={isModalActive} setIsModalActive={setIsModalActive}>
          <button onClick={() => signIn()}>Sign in</button>
          <LoginForm>
          </LoginForm>
        </Modal>
      </div>

  )
}
